### ISSUE TITLE
add xtables?

### ISSUE THREAD

**Issue by nu1ee** [blackfuel/asuswrt-rt-ac86u#1]
Can AC86U be able to add, I try to add but are missing the header file scatterlist.h

**Comment by blackfuel** [comment]
I have successfully done this in my custom Asuswrt firmware.  You need change two Makefiles in Asuswrt.  Following examples for how you could do such a thing:

**HOWTO: add xtables-addons _kernel_ modules to Linux**
https://github.com/blackfuel/asuswrt-merlin.382/blob/master/release/src-rt/Makefile#L4087

**HOWTO: add xtables-addons _userspace_ modules to iptables**
https://github.com/blackfuel/asuswrt-merlin.382/blob/master/release/src/router/Makefile#L6705
